[paths]
std2_exec = "/software/kemi/std2/2.0.1/bin/std2"
xtb4stda_exec = "/software/kemi/std2/xtb4stda/bin/xtb4stda"
std2_default_ax = "0.25"
std2_default_e = "7.0"

[dependencies]
setup = """
export OMP_STACKSIZE=4G
ulimit -s unlimited"""
